export const CONSTANTES = {
    PHYSIQUE: 'PHYSIQUE',
    MORALE: 'MORALE',
    CNI: 'CNI',
    CEDEAO: 'CEDEAO',
    PASSEPORT: 'PASSEPORT',
    SOUSCRIPTION: 'SOUSCRIPTION',
    souscription: 'souscription',
    PAIEMENT: 'PAIEMENT',
    COULEUR: 'Couleur',
    LOGO: 'Image',
    HASFORMULE: 'hasFormule',
    FALSE: 'false',
    TRUE: 'true',
    DEFAULTCOLOR: 'default-color',
    COLORDEFAULT: '--ColorDefault',
    PRIMARYCOLOR: 'primary-color',
    COLORPRIMARY: '--ColorPrimary',
    LOGOIMAGE: '--LogoImage',
    SEXE: {
        FEMININ: 'Féminin',
        MASCULIN: 'Masculin'
    },
    CONDITION: {
        GENERALES: 'generales',
        PARTICULIERES: 'particulieres'
    },
    TYPEACTION: {
        NEW: 'new',
        EDIT: 'edit'
    },
    TYPEACTIONLABEL: {
        new: 'Ajouter',
        edit: 'Modifier',
        cancel: 'Annuler'
    },
    frequences: [
        {name: 'MENSUELLE', value: 'MENSUELLE'},
        {name: 'BIMESTRIELLE', value: 'BIMESTRIELLE'},
        {name: 'TRIMESTRIELLE', value: 'TRIMESTRIELLE'},
        {name: 'SEMESTRIELLE', value: 'SEMESTRIELLE'},
        {name: 'ANNUELLE', value: 'ANNUELLE'}

    ], typeRachat: [
        {name: 'RACHAT PARTIEL', value: 'PARTIEL'},
        {name: 'RACHAT TOTAL', value: 'TOTAL'},
        {name: 'AVANCE', value: 'AVANCE'},


    ],typePaiement: [
        {name: 'VIREMENT', value: 'VIREMENT'},
        {name: 'MOBILE', value: 'MOBILE'},
    ],

    statutList: {
        DECLARE: 'DECLARE',
        AFFECTE: 'AFFECTE',
        REFUSE: 'REFUSE',
        REJETE: 'REJETE',
        EN_COURS: 'EN_COURS',
        TERMINE: 'TERMINE',
        ACCEPTE: 'ACCEPTE',
        REGLER: 'REGLER',
        EN_ATTENTE_SIGNATURE: 'EN_ATTENTE_SIGNATURE',
        EN_ATTENTE_REGLEMENT: 'EN_ATTENTE_REGLEMENT',
        DELIVRÉ: 'DÉLIVRÉ',
        EN_ATTENTE: 'EN_ATTENTE',
    },

    statusClasses: [
        {statut: 'DECLARE', classe: 'badge-blue', label: 'Déclaré'},
        {statut: 'EN_ATTENTE_SIGNATURE', classe: 'badge-warning', label: 'Attente signature'},
        {statut: 'EN_ATTENTE', classe: 'badge-warning', label: 'En attente'},
        {statut: 'EN_ATTENTE_REGLEMENT', classe: 'badge-yellow', label: 'Attente règlement'},
        {statut: 'REGLER', classe: 'badge-success', label: 'Réglé'},
        {statut: 'AFFECTE', classe: 'badge-warning', label: 'Affecté'},
        {statut: 'REFUSE', classe: 'badge-red', label: 'Refusé'},
        {statut: 'REJETE', classe: 'badge-red', label: 'Rejeté'},
        {statut: 'EN_COURS', classe: 'badge-warning', label: 'En cours'},
        {statut: 'TERMINE', classe: 'badge-success', label: 'Terminé'},
        {statut: 'ACCEPTE', classe: 'badge-success', label: 'Accepté'},
        {statut: 'DELIVRÉ', classe: 'badge-success', label: 'Délivré'},
        {statut: 'GENERE', classe: 'badge-blue', label: 'Genere'},
        {statut: 'PAYE', classe: 'status-success', label: 'Payé'},
        {statut: 'PAYE_EN_ATTENTE_VALIDATION', classe: 'status-orange', label: 'Attente validation'},
        {statut: 'RETOURNE', classe: 'badge-red', label: 'Retourne'},
    ],
    DialogTitles: {
        EDIT: 'Modifier la demande',
        ADD: 'Ajouter une demande',
    },
    labels: {
        DECLARE: 'Déclaré',
        AFFECTE: 'Affecté',
        REJETE: 'Rejeté',
        REFUSE: 'Refusé',
        EN_COURS: 'En cours',
        TERMINE: 'Terminé',
        ACCEPTE: 'Accepté',
    },
    statuts: [
        {name: 'Tous', value: ''},
        {name: 'Rejeté', value: 'REJETE'},
        {name: 'Attente signature', value: 'EN_ATTENTE_SIGNATURE'},
        {name: 'Attente règlement', value: 'EN_ATTENTE_REGLEMENT'},
        {name: 'Reglé', value: 'REGLER'},],

    TYPEDOCUMENT: {
        CNI: 'CNI',
        FICHE: 'Fiche',
        DOC: '.doc',
        PDF: '.pdf',
        RAPPORTMEDICAL: 'MEDICAL',
        CERTIFICATGENREMORT: 'MORT',
        FICHEENTREEALAMORGUE:'MORGUE',
        CERTIFICATDECES: 'DECES',
        RAPPORTPOLICEOUGENDARMERIE: 'POLICE',
        DEMANDERESILIATION: 'résiliation'
    },
    STATUT: {
        RESILIER: 'RESILIE',
        REGLER: 'REGLER',
        ENCOURS: 'EN_COURS',
        ENATTENTE: 'EN_ATTENTE',
        AVECRADIATION: 'AVEC_RADIATION',
        RETOURNER: 'RETOURNE',
        PENDING: 'PENDING',
        PAYE: 'PAYE',
        PAYEENATTENTEVALIDATION:'PAYE_EN_ATTENTE_VALIDATION',
        EXPIRER: 'EXPIRE',
        RENOUVELE: 'RENOUVELLE',
        DECLARE: 'DECLARE',
        RADIER: 'RADIE',
        CONTENTIEUX: 'CONTENTIEUX',
        IMPAYE: 'IMPAYE',
        RAPPEL: 'RAPPEL',
        ATTENTEVISITEMEDICAL: 'ATTENTE_VISITE_MEDICAL',
        EXPIREBIENTOT: 'EXPIRE_BIENTOT',
        GENERE: 'GENERE',
        REJETE: 'REJETE',
        RETOURNE: 'RETOURNE',
        CLOTURER: 'CLOTURER',
        PLANIFIER: 'PLANIFIER',
        DEMARRER: 'DEMARRER',
        TERMINER: 'TERMINER',
    },
    TYPESINISTRE: {
        INVALIDITE: 'INVALIDITE',
        DECES: 'DECES',
        CODEDECES: 'TD'
    },
    ETAPESINISTRE: {
        FINAL: 'VALIDATION_FINALE',
        CONFORMITE: 'VALIDATION_CONFORMITE',
        VERIFICATION: 'VERIFICATION'
    },
    MENUGROUP: {
        GROUP: '1',
        COLLAPSABLE: '2',
        BASIC: '3'
    },
    TYPE: {
        ASSURE: 'assure',
        CONSULTER: 'consulter',
        AFFECTER: 'affecter',
        MANAGE_FORMULES: 'manage-formules',
        RENOUVELLEMENT: 'renouvellement',
        GENERALES: 'generales',
        PARTICULIERES: 'particulieres',
        RESILIER: 'resilier',
        RENONCE: 'renonce',
        ATTENTEVISITEMEDICAL: 'attente-visite-medical',
        STATU: 'statu',
        SINISTRE:'sinistre',
        SUPPRIMER: 'supprimer',
        MODIFIER: 'modifier',
        CONFIGURER: 'configurer',
        DETAILS: 'details',
        DETAIL: 'detail',
        DETAILFORM: 'detaill',
        DETAILLIST: 'detailListe',
        VOIR: 'voir',
        SUIVI: 'suivi',
        REGLEMENT:'reglement',
        ACTIVER: 'activeDesactiv',
        CONTRAT: 'contrats',
        FORMULES: 'foumules',
        RACHAT: 'rachat',
        DETAILPARTENAIRE: 'detailsPartenaire',
        DETAILGROUPEUSERS: 'detailsGU',
        DETAILCAMPAGNE: 'detailsCampagne',
        DEMARRER: 'demarrer',
        CLOTURER: 'cloturer',
        CAMPAGNE: 'campagne',
        PRODUITDETAIL: 'detailProduit',
        DETAILMORTALITE:'detailMortalite',
        FORMULE_DETAIL: 'detailFormule',
    },
    ITEMTYPE: {
        PASSWORD: 'password',
        TEXT: 'text'
    },
    URLPARAMETREFTP: 'parametre-ftp',
    CODE: {
        EDUCATION: 'ED',
        RETRAITE: 'RC',
        DECES: 'TD'
    },
    NOTIFICATIONTYPE: {
        EMAIL: 'EMAIL',
        SMS: 'SMS'
    },
    ROLETYPE: {
        COMMERCIALE: 'ROLE_COMMERCIALE',
        COMMERCIALES: 'ROLE_COMMERCIALES',
        RESPONSABLE_COMMERCIALE: 'ROLE_RESPONSABLE_COMMERCIALE',
        ADMINISTRATEUR: 'ROLE_ADMINISTRATEUR',
        SOUSCRIPTEUR: 'ROLE_SOUSCRIPTEUR',
        USER: 'ROLE_USER',
        ADMIN: 'ROLE_ADMIN',
        MEDECIN: 'ROLE_MEDECIN',
        COMPTABLE: 'ROLE_COMPTABLE',
        AGENT_SINITRE: 'ROLE_AGENT_SINISTRE',
        IMF:'ROLE_IMF',
        DEX:'ROLE_DIRECTEUR_EXPERIENCE',
        DOP:'ROLE_DIRECTEUR_OPERATION',
        DFC:'ROLE_DIRECTEUR_FINANCE_COMPTA',
        APPORTEUR_AFFAIRE:'ROLE_APPORTEUR_AFFAIRE',
        PARTENAIRE:'ROLE_PARTENAIRE',
        LABORATOIRE:'ROLE_LABORATOIRE',
    },
    DEMANDETYPE: {
        PRELEVEMENT: "PRELEVEMENT",
        RACHAT: "RACHAT",
        REMBOURSEMENT: "REMBOURSEMENT",
        RECLAMATION: "RECLAMATION"
    },
    TYPEPRODUIT: {
        ETUDE: 'ETUDE',
        DECES: 'DECES',
        RETRAITE: 'RETRAITE',
        RETRAITEMIX: 'RETRAITE_MIX',
    },
    NIVEAU : {
        CHEF_RESEAU: 'CHEF_RESEAU',
        CHEF_UNITE : 'CHEF_UNITE',
        CHEF_EQUIPE : 'CHEF_EQUIPE',
        COMMERCIAL : 'COMMERCIAL',
        CRS : 'CRS',
        CUN : 'CUN',
        CEQ : 'CEQ',
        COM : 'COM',
        INS: 'INS',
    },
    CATEGORIEPRODUIT: {
        IMF: 'IMF',
        MOBILE: 'MOBILE',
        COLLECTIFEMPRUNTEUR: 'COLLECTIF_EMPRUNTEUR',
        DIGITALE: 'DIGITALE',
    },

    //start for api
    HTTP_STATUS : {
        SUCCESSFUL : 200,
        UNAUTHORIZED : 401,
        INVALIDATE : 503,
        OPTSENT : 300,
    },
    RESPONSE_DATA : 'data',
    RESPONSE_CODE : 'responseCode',


}
